# Powerlevel10k config. Hand-authored rather than generated by `p10k configure`
# -- the wizard emits ~1700 lines of mostly-defaults, which is unreviewable in a
# dotfiles repo. Only deviations from p10k's defaults live here.
#
# Palette is deliberately cool (blues / cyans / slate / cool violet) to sit
# against a warm terminal theme without clashing. 256-color codes throughout so
# it renders the same regardless of the terminal's 16-color ANSI mapping.

# Temporarily disable aliases and set sane options while this file loads.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # ---------------------------------------------------------------- segments
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs newline prompt_char)
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status command_execution_time background_jobs direnv
    virtualenv nodejs_version rust_version context time
  )

  # Lean look: no powerline blocks, no segment backgrounds, no icon padding.
  typeset -g POWERLEVEL9K_BACKGROUND=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=
  typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION=
  typeset -g POWERLEVEL9K_ICON_PADDING=none
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR=' '

  # ------------------------------------------------------------ prompt char
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=80
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=205
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_{LEFT,RIGHT}_WHITESPACE=
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true

  # -------------------------------------------------------------------- dir
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=75
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=117
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
  # Shorten middle components, keeping anything "anchor"-worthy (repo roots,
  # dirs holding package.json / Cargo.toml / .git) legible in full.
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
  typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=80
  typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=v3
  typeset -g POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND=205

  # -------------------------------------------------------------------- vcs
  # Cool-only git states. Distinguished by hue within the blue/violet range
  # rather than the usual green/yellow/red, which would reintroduce warmth.
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=79
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=111
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=140
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=205
  typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=244
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=

  # This is the setting that keeps big worktrees (node_modules, target, vendor,
  # data-dir) from stalling the prompt: past this many files in the index, skip
  # the dirty check entirely and report branch/ahead/behind only. Without it,
  # p10k degrades the same way starship's scan_timeout did.
  typeset -g POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY=8192
  # Never block the prompt on git; paint VCS in asynchronously once ready.
  typeset -g POWERLEVEL9K_VCS_MAX_SYNC_LATENCY_SECONDS=0.05

  # ----------------------------------------------------------------- status
  # Only surface failures; a zero exit is just the prompt char turning cyan.
  typeset -g POWERLEVEL9K_STATUS_OK=false
  typeset -g POWERLEVEL9K_STATUS_ERROR=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=205
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=205
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=205
  typeset -g POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false

  # -------------------------------------------------------------- execution
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=103
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT=d

  # ------------------------------------------------------------- misc right
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=110
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
  typeset -g POWERLEVEL9K_DIRENV_FOREGROUND=103
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=110
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
  typeset -g POWERLEVEL9K_NODEJS_VERSION_FOREGROUND=108
  typeset -g POWERLEVEL9K_NODEJS_VERSION_PROJECT_ONLY=true
  typeset -g POWERLEVEL9K_RUST_VERSION_FOREGROUND=109
  typeset -g POWERLEVEL9K_RUST_VERSION_PROJECT_ONLY=true

  # Only show user@host over SSH or as root -- noise on a local machine.
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=205
  typeset -g POWERLEVEL9K_CONTEXT_REMOTE{,_SUDO}_FOREGROUND=103
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_CONTENT_EXPANSION=

  typeset -g POWERLEVEL9K_TIME_FOREGROUND=244
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false

  # Redraw the prompt in place when an async segment resolves.
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  (( ! $+functions[p10k] )) || p10k reload
}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
