[tools]
# Devtools
hurl = "8.0.1"

# Runtimes and CLIs
detox = "latest"
eza = "latest"
elixir = "1.19.5"
erlang = "28.5"
"github:Ataraxy-Labs/lazydiff" = "0.1.0-alpha.7"
"github:agavra/tuicr" = "latest"
gh = "latest"
go = "latest"
helm = "latest"
java = "latest"
lazygit = "latest"
neovim = "latest"
node = "26.1.0"
python = "3.13.13"
rclone = "latest"
ripgrep = "latest"
ruby = "3.4.5"
rust = "latest"
btop = "1.2.13"

[settings]

[settings.ruby]
compile = false
